# -*- coding: utf-8 -*-
"""DownloadDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIkmXXJH9Xf9DAiXtRSdfWXBifbR4pIj
"""

pip install wget

import wget

url = "https://s3.amazonaws.com/fast-ai-nlp/imdb.tgz"

wget.download(url)

import tarfile

tf  = tarfile.open("/content/imdb.tgz")

tf.extractall()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# %cd imdb/

import pandas as pd
import numpy as np



